### ISSUE TITLE
3.Gamepad, jesli prawy grzyb jest w pozycji neutralnej, to strzały pojawiają się na środku tekstury gracza strzelającego, co powoduje natychmiastowy zgon.  

### ISSUE THREAD

**Issue by Brodie0** [Brodie0/GunsBullets#3]

**Comment by DragoonAethis** [comment]
Tak btw to strzał myszką celując zbyt blisko gracza powoduje to samo xD

Zamiast tego będzie chyba lepiej liczyć tylko kąt obrotu gracza, i wg tego obrotu od Player.Origin utworzyć pocisk o ileśtam px oddalony, gdzie (X, Y) z tego liczone byłoby na podstawie obrotu gracza, nie pozycji myszy - hmm, może nowy pocisk, gdzie zawsze byłby w pozycji Player.Origin + (0, (PlayerTexture.Height / 2) + 5), ustawić Bullet.Origin na Player.Origin, wtedy Bullet.Rotate(Player.Rotation), Bullet.Origin = Bullet.Position (+- wys/szer teksturki aby był na środku), i Bullet.Rotation = Player.Rotation - każdy ruch kuli na podstawie obrotu (mniej do przesłania przy okazji). Na to są chyba jakieś fajne sin/cosy które załatwiają liczenie nowych (X, Y) w jakiś prosty sposób bez tej rotacji itd?

**Comment by DragoonAethis** [comment]
Zrobione, od teraz wszystko zależy od obrotu gracza i GameInput.AimingDirection, który jest znormalizowanym wektorem (znormalizowany tj jego długość to 1 - więc mamy sobie "wychodzącą z punktu" wektorową strzałeczkę wskazującą w którą stronę patrzymy, niezależnie od tego jak daleko jest kursor/wysunięty grzybek na padzie).
