### ISSUE TITLE
5.Pociski w ścianach, nie znikają od razu ( nie mam pojecia co jest nie tak w kodzie). Pociski potrafią przelatywać przez niektóre "rogi" ścian.

### ISSUE THREAD

**Issue by Brodie0** [Brodie0/GunsBullets#4]

**Comment by DragoonAethis** [comment]
Częściowo naprawione - pociski wewnątrz ścian będą znikać od razu (i nie będą rysowane jeszcze przed usunięciem z list), i jeśli pocisk "trafi" w róg to równiez rozważamy czy usunąć go czy rykoszet.

Czasem jest problem taki że pocisk powinien trafić w róg, ale prędkość pocisku jest za duża i [przez niego przelatuje](https://imgur.com/a/EWzfd) - w takim przypadku pierwsze sprawdzenie czy pocisk trafi nie wykryje kolizji bo pocisk jest przed rogiem, a drugie sprawdzenie będzie widziało pocisk już za ścianą.

Trzeba by to "porządnie" zrobić używając [promieni](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.ray_members.aspx) i testu czy następny ruch pocisku danym promieniem spowoduje uderzenie w ścianę (kolizje FNA takie coś w sobie mają - `BoundingBox.Intersects(Ray ray)`), ale mamy teraz większe problemy (np crashe :P) więc na razie uznaję to za zamknięte.
